on: push


name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Install dependicies
        run: pnpm install
      - name: Install vsce
        run: pnpm add -g @vscode/vsce
      - name: publish extension
        env:
            VSCE_PAT: ${{ secrets.VS_MARKETPLACE_TOKEN }}
        run: |
          pnpm --no-dependencies vsce publish --pat $VSCE_PAT
          